import type { StudyResult } from './analyze.ts';

/**
 * Sample sizes below which a per-vendor row says more about who happened to be
 * sampled than about the vendor. Rows under the floor are still printed — the
 * corpus should be visible — but flagged so nobody cites them as a ranking.
 */
const MIN_REPOS_FOR_VENDOR_SIGNAL = 5;
const MIN_THREADS_FOR_VENDOR_SIGNAL = 50;

/** Console-only summary. Deliberately not written into the public report. */
export function verdict(r: StudyResult): { label: string; detail: string } {
  const c = r.coverage.pctReposWith2Plus;
  const n = r.sample.reposScanned;
  return {
    label: `${c}% run 2+`,
    detail: `${r.coverage.pctReposWithAnyAi}% run at least one AI reviewer; ` +
      `${c}% run two or more; duplicate rate ${r.duplication.pctOverlapping}% (n=${n}).`,
  };
}

export function toMarkdown(r: StudyResult): string {
  const lines: string[] = [];
  const p = (s = '') => lines.push(s);

  p('# AI Code Review Census — current results');
  p();
  p(`_Generated ${r.generatedAt} · ${r.sample.reposScanned} repositories · ${r.sample.pullsScanned} pull requests_`);
  p();
  p('Generated by `src/main.ts`. Every number is recomputable from `data/scans.jsonl`.');
  p();

  if (r.sample.reposScanned < 300) {
    p(`> **Preliminary.** The corpus is ${r.sample.reposScanned} repositories and still growing. ` +
      'Percentages move by several points as it does. Treat these as directional.');
    p();
  }

  p('## Adoption');
  p();
  p('| Metric | Value |');
  p('| --- | --- |');
  p(`| Repos with **any** AI reviewer | ${r.coverage.pctReposWithAnyAi}% (${r.coverage.reposWithAnyAi}/${r.sample.reposScanned}) |`);
  p(`| Repos with **2+** AI reviewers | ${r.coverage.pctReposWith2Plus}% (${r.coverage.reposWith2Plus}/${r.sample.reposScanned}) |`);
  p(`| Repos with **3+** AI reviewers | ${r.coverage.pctReposWith3Plus}% (${r.coverage.reposWith3Plus}/${r.sample.reposScanned}) |`);
  p(`| PRs with at least one AI review | ${r.sample.pullsWithAnyAiReview} / ${r.sample.pullsScanned} |`);
  p();

  p('## Duplication between reviewers');
  p();
  p(`Measured only on the ${r.duplication.multiBotPulls} pull requests where two or more ` +
    'vendors both commented. A collision is two threads from different vendors on the ' +
    `same file within ${5} lines.`);
  p();
  p(`**${r.duplication.pctOverlapping}%** of AI threads on those PRs collide with a rival's ` +
    `(${r.duplication.overlappingPairs} collisions).`);
  p();

  p('## Action proxy');
  p();
  p('| Author | Threads | Code changed afterwards |');
  p('| --- | ---: | ---: |');
  p(`| Humans | ${r.sample.threadsFromHumans} | ${r.action.humanActionRate}% |`);
  p(`| AI reviewers | ${r.sample.threadsFromAi} | ${r.action.aiActionRate}% |`);
  p();

  p('## Per-vendor');
  p();
  p('> **This is not a ranking.** Rows marked ⚠ are below the sample floor ' +
    `(${MIN_REPOS_FOR_VENDOR_SIGNAL} repositories or ${MIN_THREADS_FOR_VENDOR_SIGNAL} threads) ` +
    'and say more about which repositories happened to be sampled than about the vendor. ' +
    'The table is published so the composition of the corpus is visible, not to compare tools.');
  p();
  p('| Vendor | Repos | PRs | Threads | Per PR | Action rate | Resolved | Avg length |');
  p('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const s of r.vendors) {
    const thin =
      s.repos < MIN_REPOS_FOR_VENDOR_SIGNAL || s.threads < MIN_THREADS_FOR_VENDOR_SIGNAL;
    p(
      `| ${thin ? '⚠ ' : ''}${s.vendor} | ${s.repos} | ${s.pulls} | ${s.threads} | ${s.threadsPerPull} | ` +
        `${s.actionRate}% | ${s.resolveRate}% | ${s.avgBodyLength} |`,
    );
  }
  p();
  p('_Action rate = share of inline threads whose anchored code changed afterwards ' +
    '(GitHub marks the thread outdated). It is a proxy, not proof — an unrelated edit ' +
    'to the same region also outdates a thread. It is also biased toward reviewers that ' +
    'comment early in a PR\'s life, since more subsequent commits can outdate their threads. ' +
    'Resolve rate is reported alongside for that reason._');
  p();

  if (r.duplication.topCollidingPairs.length) {
    p('## Which bots step on each other');
    p();
    p(`Measured only on the ${r.duplication.multiBotPulls} PRs where 2+ vendors both commented.`);
    p();
    p('| Pair | Colliding threads |');
    p('| --- | ---: |');
    for (const c of r.duplication.topCollidingPairs) p(`| ${c.pair} | ${c.count} |`);
    p();
  }

  if (r.languages.length) {
    p('## By primary language');
    p();
    p('| Language | Repos | 2+ AI reviewers |');
    p('| --- | ---: | ---: |');
    for (const l of r.languages) p(`| ${l.language} | ${l.repos} | ${l.pctWith2Plus}% |`);
    p();
  }

  if (r.unclassifiedBots.length) {
    p('## Unclassified bots');
    p();
    p('Logins ending in `[bot]` not in the registry. Reviewed manually before being ' +
      'added — guessing them into the AI-reviewer bucket would corrupt the headline number.');
    p();
    for (const u of r.unclassifiedBots) p(`- \`${u.login}\` — ${u.count}`);
    p();
  }

  p('## Method and limitations');
  p();
  p('- **Sample frame:** public, non-archived repos above a star floor with a recent push, ' +
    'taken from GitHub search ordered by last update. Biased toward popular open source ' +
    'and away from private corporate monorepos, where multi-bot adoption is plausibly higher. ' +
    'The headline number is therefore best read as a **lower bound**.');
  p('- **Per-repo depth:** the most recently updated PRs only, so a repo that adopted a ' +
    'second reviewer years ago and dropped it will not register.');
  p('- **Action rate** relies on GitHub\'s `isOutdated` flag, described above.');
  p('- **Bot identification** is an explicit allow-list of known logins. New or self-hosted ' +
    'reviewers under custom app names are undercounted.');
  p('- No LLM is used anywhere in this analysis. Every number is reproducible from the raw ' +
    'scans in `data/scans.jsonl`.');
  p();

  return lines.join('\n');
}
